// SPDX-FileCopyrightText: 2023 Nemanja
// SPDX-FileCopyrightText: 2023 Vasilis
// SPDX-FileCopyrightText: 2024 Aexxie
// SPDX-FileCopyrightText: 2024 Debug
// SPDX-FileCopyrightText: 2024 FoxxoTrystan
// SPDX-FileCopyrightText: 2024 Psychpsyo
// SPDX-FileCopyrightText: 2024 SimpleStation14
// SPDX-FileCopyrightText: 2024 Sk1tch
// SPDX-FileCopyrightText: 2024 SlamBamActionman
// SPDX-FileCopyrightText: 2024 Spatison
// SPDX-FileCopyrightText: 2024 deathride58
// SPDX-FileCopyrightText: 2024 metalgearsloth
// SPDX-FileCopyrightText: 2025 Dirius77
// SPDX-FileCopyrightText: 2025 DocNITE
// SPDX-FileCopyrightText: 2025 Falcon
// SPDX-FileCopyrightText: 2025 RedFoxIV
// SPDX-FileCopyrightText: 2025 portfiend
// SPDX-FileCopyrightText: 2025 sev7ves
// SPDX-FileCopyrightText: 2025 sleepyyapril
//
// SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

using Content.Shared._DEN.CCVars;
using Content.Shared.Weapons.Ranged.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;


namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class DenTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public DenTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AutoFormatterEnabled.Pressed = _cfg.GetCVar(DenCCVars.AutoFormatterEnabled);
        RemoveAsterisksFromEmotes.Pressed = _cfg.GetCVar(DenCCVars.RemoveAsterisksFromEmotes);
        ShowTypingRangeOnShortRange.Pressed = _cfg.GetCVar(DenCCVars.ShowTypingRange);

        SetDefaultColors();

        AutoFormatterEnabled.OnToggled += OnCheckBoxToggled;
        RemoveAsterisksFromEmotes.OnToggled += OnCheckBoxToggled;
        ShowTypingRangeOnShortRange.OnToggled += OnCheckBoxToggled;

        DialogueColorSelector.OnColorChanged += OnDialogueColorChanged;
        EmoteColorSelector.OnColorChanged += OnEmoteColorChanged;

        ApplyButton.OnPressed += OnApplyButtonPressed;
        UpdateApplyButton();
    }

    private void OnDialogueColorChanged(Color color)
    {
        var previewText = Loc.GetString("ui-options-preview-placeholder");
        DialoguePreviewLabel.Text = $"[color={color.ToHex()}]{previewText}[/color]";
    }

    private void OnEmoteColorChanged(Color color)
    {
        var previewText = Loc.GetString("ui-options-preview-placeholder");
        EmotePreviewLabel.Text = $"[color={color.ToHex()}]{previewText}[/color]";
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args) => UpdateApplyButton();

    private void SetDefaultColors()
    {
        var dialogueColorSaved = _cfg.GetCVar(DenCCVars.DialogueColor);
        var dialogueColor = Color.FromHex(dialogueColorSaved);

        var emoteColorSaved = _cfg.GetCVar(DenCCVars.EmoteColor);
        var emoteColor = Color.FromHex(emoteColorSaved);

        DialogueColorSelector.Color = dialogueColor;
        EmoteColorSelector.Color = emoteColor;

        OnDialogueColorChanged(dialogueColor);
        OnEmoteColorChanged(emoteColor);
    }

    private void OnApplyButtonPressed(BaseButton.ButtonEventArgs args)
    {
        _cfg.SetCVar(DenCCVars.AutoFormatterEnabled, AutoFormatterEnabled.Pressed);
        _cfg.SetCVar(DenCCVars.RemoveAsterisksFromEmotes, RemoveAsterisksFromEmotes.Pressed);
        _cfg.SetCVar(DenCCVars.ShowTypingRange, ShowTypingRangeOnShortRange.Pressed);

        _cfg.SetCVar(DenCCVars.DialogueColor, DialogueColorSelector.Color.ToHex());
        _cfg.SetCVar(DenCCVars.EmoteColor, EmoteColorSelector.Color.ToHex());

        _cfg.SaveToFile();
        UpdateApplyButton();
    }

    private void UpdateApplyButton()
    {
        var isAutoFormatterSame = AutoFormatterEnabled.Pressed == _cfg.GetCVar(DenCCVars.AutoFormatterEnabled);
        var isRemoveAsterisksSame = RemoveAsterisksFromEmotes.Pressed == _cfg.GetCVar(DenCCVars.RemoveAsterisksFromEmotes);
        var isShowTypingRangeSame = ShowTypingRangeOnShortRange.Pressed == _cfg.GetCVar(DenCCVars.ShowTypingRange);

        var isDialogueColorSame = DialogueColorSelector.Color.ToHex() == _cfg.GetCVar(DenCCVars.DialogueColor);
        var isEmoteColorSame = EmoteColorSelector.Color.ToHex() == _cfg.GetCVar(DenCCVars.EmoteColor);

        ApplyButton.Disabled = isAutoFormatterSame
            && isRemoveAsterisksSame
            && isShowTypingRangeSame
            && isDialogueColorSame
            && isEmoteColorSame;
    }
}
