// SPDX-FileCopyrightText: 2025 Cam
// SPDX-FileCopyrightText: 2025 Cami
// SPDX-FileCopyrightText: 2025 sleepyyapril
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Systems.Chat.Widgets;
using Content.Shared._DEN.CCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;


namespace Content.Client.UserInterface.Systems.Chat.Controls.Denu;


[GenerateTypedNameReferences]
public sealed partial class DenuWindow : AnimatedWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = null!;

    private const string PreviewText = "\"Hello! *italic* **bold** ***bolditalic***\" *looks at you*";

    private readonly DenuUIController _denuUIController;
    private readonly IClientConsoleHost _consoleHost;

    public DenuWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _denuUIController = UserInterfaceManager.GetUIController<DenuUIController>();
        _consoleHost = IoCManager.Resolve<IClientConsoleHost>();
        InitializeUI();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        UpdateLivePreview();
        base.FrameUpdate(args);
    }

    private void InitializeUI()
    {
        SetupWindow();
        SetupEventHandlers();
        SetCVarDefaults();
        SetupColorSelectors();
        SetupHelpDisplay();
        UpdateExamplePreview();
    }

    private void SetupWindow()
    {
        Title = "Denu";
        Tabs.SetTabTitle(0, "Chat");
        Tabs.SetTabTitle(1, "Preview");
        Tabs.SetTabTitle(2, "Help");

        HelpButton.Visible = true;
        HelpButton.Disabled = false;
    }

    private void SetupEventHandlers()
    {
        HelpButton.OnPressed += _ => Tabs.CurrentTab = 2;
        CloseButton.OnPressed += _ => Close();

        TypingToggleButton.WhileToggled += _denuUIController.ShowTypingIndicator;
        TypingToggleButton.OnToggledOff += _denuUIController.HideTypingIndicator;
        _consoleHost.AnyCommandExecuted += (_, _, _, _) => TypingToggleButton.Pressed = false;
        EarmuffSlider.OnReleased += slider => OnEarmuffSliderChanged(slider.Value, true);
        EarmuffSlider.OnValueChanged += slider => OnEarmuffSliderChanged(slider.Value);

        AutoFormatterCheckBox.OnToggled += args => OnAutoFormatterPressed(args.Pressed);
        RemoveAsterisksCheckBox.OnToggled += args => OnRemoveAsterisksChanged(args.Pressed);
        ShowTypingRange.OnToggled += args => OnShowTypingRangeChanged(args.Pressed);
    }

    private void OnAutoFormatterPressed(bool value) =>
        _denuUIController.AutoFormatterEnabled = value;

    private void OnRemoveAsterisksChanged(bool value)
    {
        _denuUIController.FormatterConfig.RemoveAsterisks = value;
        UpdateExamplePreview();
        UpdateLivePreview();
    }

    private void OnShowTypingRangeChanged(bool value)
    {
        _denuUIController.SetShouldUseTypingCircleOverlay(value);
    }

    private void SetupColorSelectors()
    {
        DialogueColorSelector.Color = _denuUIController.GetColorReplacement("DialogueColor");
        DialogueColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;
        DialogueColorSelector.OnColorChanged += c => HandleColorChanged("DialogueColor", c);

        EmoteColorSelector.Color = _denuUIController.GetColorReplacement("EmoteColor");
        EmoteColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;
        EmoteColorSelector.OnColorChanged += c => HandleColorChanged("EmoteColor", c);
    }

    private void SetupHelpDisplay()
    {
        HelpDisplay.Formatter = text => _denuUIController.FormatMessage(text);
    }

    private void SetCVarDefaults()
    {
        AutoFormatterCheckBox.Pressed = _cfg.GetCVar(DenCCVars.AutoFormatterEnabled);
        RemoveAsterisksCheckBox.Pressed = _cfg.GetCVar(DenCCVars.RemoveAsterisksFromEmotes);
        ShowTypingRange.Pressed = _cfg.GetCVar(DenCCVars.ShowTypingRange);

        var dialogueColorSaved = _cfg.GetCVar(DenCCVars.DialogueColor);
        var emoteColorSaved =  _cfg.GetCVar(DenCCVars.EmoteColor);

        var dialogueColor = Color.FromHex(dialogueColorSaved);
        var emoteColor = Color.FromHex(emoteColorSaved);

        _denuUIController.SetColorReplacement("DialogueColor", dialogueColor);
        _denuUIController.SetColorReplacement("EmoteColor", emoteColor);

        OnAutoFormatterPressed(AutoFormatterCheckBox.Pressed);
        OnRemoveAsterisksChanged(RemoveAsterisksCheckBox.Pressed);
        OnShowTypingRangeChanged(ShowTypingRange.Pressed);
    }

    private void HandleColorChanged(string replacementName, Color color)
    {
        _denuUIController.SetColorReplacement(replacementName, color);
        UpdateExamplePreview();
    }

    private void UpdateExamplePreview()
    {
        var exampleText = GetExampleText();
        ExamplePreview.SetMarkup(exampleText);
        HelpDisplay.ForceReformat();
    }

    private void UpdateLivePreview()
    {
        var currentMessage = GetCurrentChatMessage();
        LargeLivePreview.SetMarkup(currentMessage);
    }

    private string GetChatInputText() =>
        UserInterfaceManager.ActiveScreen?.GetWidget<ChatBox>()?.ChatInput?.Input.Text ??
        UserInterfaceManager.ActiveScreen?.GetWidget<ResizableChatBox>()?.ChatInput?.Input.Text ??
        "";

    private string GetExampleText()
    {
        var formattedPreview = _denuUIController.FormatMessage(PreviewText);
        return $"{PreviewText}\n{formattedPreview}";
    }

    private string GetCurrentChatMessage()
    {
        var message = GetChatInputText();
        return string.IsNullOrWhiteSpace(message) ? GetExampleText() : _denuUIController.FormatMessage(message);
    }

    private void OnEarmuffSliderChanged(float sliderValue, bool sendUpdate = false)
    {
        var rounded = (float) Math.Round(sliderValue, 2);
        EarmuffDistanceLabel.Text = sliderValue.ToString("F1");
        _denuUIController.SetEarmuffRange(rounded, sendUpdate);
    }
}
